### ISSUE TITLE
Is it possible to draw a curved line?

### ISSUE THREAD

**Issue by arktisma** [simplegeo/polymaps#103]
I guess the title says it all... How could I draw a curved line between markers/points in Polymaps?

For example, let's say I wanted to draw a point in Australia to a point in Europe with curvature, much like one might see a flight route mapped?

Thanks!

**Comment by mbostock** [comment]
Take a look at D3's support for great arcs:

https://github.com/mbostock/d3/blob/master/examples/great-arc/great-arc.html
http://mbostock.github.com/d3/talk/20111116/#14
