### ISSUE TITLE
Is that nifty fullscreen arrow widget in the examples free to use?

### ISSUE THREAD

**Issue by eagereyes** [simplegeo/polymaps#107]
I'm asking because that code isn't in the repository and it looks like it has been obfuscated. Is there a reason for that?

**Comment by mbostock** [comment]
Yes, it's free to use, and the non-minified version is here:

https://github.com/simplegeo/polymaps/blob/gh-pages/_includes/fullscreen.js

**Comment by eagereyes** [comment]
Awesome, thanks!
