### ISSUE TITLE
Drawing lines across 180º longitude wraps them the wrong way

### ISSUE THREAD

**Issue by eagereyes** [simplegeo/polymaps#109]
Another issue coming out of the ZIPScribble map project, this time with Russia. That country inconveniently sticks out across 180º longitude. When drawing a line from just below 180º to just above 180º, polymaps draws a very long line from one end of the map to the other. Using negative values or values above 180 doesn't make any difference. I think there should be a convention so that values over 180º are drawn to the east, rather than wrapping around and appearing in the far west.

**Comment by mbostock** [comment]
Duplicate of #33. I think it's supposed to work with values above +180º and below -180º.
