### ISSUE TITLE
Firefox 11 map.size Issue

### ISSUE THREAD

**Issue by ghost** [simplegeo/polymaps#115]
Firefox 11 update breaks longstanding SVG transformation. This seems to suggest Firefox is enforcing something not
enforced in the past, and so ignoring certain statements.

**Comment by vkdot** [comment]
In FF 10 it was working. FF 11 Issue can be fixed by adding width and height attributes to root SVG element.

Possible work-around:

Instead of:
`var map = po.map()
    .container(document.getElementById("map").appendChild(po.svg("svg")))
    .add(po.interact())
    .add(po.hash());`

Use:
`var svg = po.svg("svg");
    svg.setAttribute('width', '100%');
    svg.setAttribute('height', '100%');
var map = po.map()
    .container(document.getElementById("map").appendChild(svg))
    .add(po.interact())
    .add(po.hash());`

**Comment by ghost** [comment]
The fix above didn't work for me. This was a easy css fix to the svg tag, added width & height 100%. This created an issue with the fullscreen toggle button.

Update:
 var f = n$(document.body),
        c = n$("#map").style("visibility", "visible"),
        b = false,
        a = c.add("svg:svg").style("position", "absolute").style("right", "-16px").style("top", "-16px").style("visibility", "visible").style("width", "32px").style("height", "32px").on("mousedown", d);

(changed .attr to .style)

**Comment by ghost** [comment]
I wouldn't call this closed yet.  The code to polymaps should be updated to fix this... not just an acceptable workaround in place.  MultimediaDeveloper, I have no clue what your code does, however I was able to make it work by using the solution from vkdot.

**Comment by gouldingken** [comment]
I second that - and also had success with the first solution. I don't think any issues should be marked as resolved until they are included in the main trunk - and until the issues can't be replicated simply by going to the examples section of the polymaps site!

**Comment by bigethan** [comment]
I would like to third that this is not a closed issue.

**Comment by sidkshatriya** [comment]
I had success with the first solution also.
