### ISSUE TITLE
Choropleth maps not working?

### ISSUE THREAD

**Issue by hamcake** [simplegeo/polymaps#116]
Hi there --
I'm interested in using Polymaps, but I notice that some of the Choropleth examples on the website aren't working. Are there known problems with this feature, or possibly breaking changes?

http://polymaps.org/ex/statehood.html
http://polymaps.org/ex/population.html
http://polymaps.org/ex/unemployment.html

Thanks!

**Comment by mbostock** [comment]
This is because Google started charging more aggressively for App Engine, and the polymaps website is over-budget (or conversely, under-funded). I think Stamen is working on hosting the tiles, but I don't know of the status

**Comment by hamcake** [comment]
I appreciate the quick response. This is good to know.

-----Original Message-----
From: Mike Bostock
[mailto:reply@reply.github.com]
Sent: March-15-12 4:49 PM
To: hamcake
Subject: Re: [polymaps] Choropleth maps not working? (#116)

This is because Google started charging more aggressively for App Engine,
and the polymaps website is over-budget (or conversely, under-funded). I
think Stamen is working on hosting the tiles, but I don't know of the status

---

**Comment by sidkshatriya** [comment]
I believe the examples are all working. Are you using Firefox? Seem that some incompatibilities were introduced with the recent versions of Firefox. Try the examples in Chrome/Safari. 

IE9 will only work with version 2.5.1. The website uses 2.5.0

**Comment by hamcake** [comment]
Yes, these are working now, though the problem I was having was due to what mbostock commented about.
