### ISSUE TITLE
Can a inline geoJSON object be added directly?

### ISSUE THREAD

**Issue by psaia** [simplegeo/polymaps#119]
I think that if I have a geoJSON object already loaded on the page I should be able to add it to the map. Though, I could be missing something. I definitely didn't see any examples of this in the API.

**Comment by mbostock** [comment]
Try [geoJson.features](http://polymaps.org/docs/geoJson.html#features).

**Comment by psaia** [comment]
Well I believe geoJson.features is not working for me because I am passing a JSON object with the type "FeatureCollection" on it. I guess there is no support for that?

**Comment by mbostock** [comment]
Wrap the object in an array, e.g., `features([myFeature])`.

**Comment by psaia** [comment]
That worked, thanks!
