### ISSUE TITLE
Polymaps not working in IE9 and Firefox 12 properly

### ISSUE THREAD

**Issue by sidkshatriya** [simplegeo/polymaps#126]
I love Polymaps and would like to use it in my next project. I'm playing around with Polymaps + Tilestache which is amazingly powerful!

Unfortunately there seem to be two issues
1) Activity on the git repo seems to have reduced to zero for quite some time.
2) Many Polymap examples are not working correctly in Firefox and IE9. E.g. the window for the map is very small and panning works properly within that for http://polymaps.org/ex/unemployment.html in Firefox -- this leads me to believe that the underlying incompatibilities are not significant. 

Things work correctly in Chrome and Safari.

I know this is a open source project -- I should probably try to fix these issues myself -- currently I don't know the code base very well. Maybe in the future ... but not currently!

Can you provide a roadmap of what you would like to do for Polymaps in the future?

**Comment by sennierer** [comment]
I have exactly the same problem. Everything worked fine until Firefox 12. Does anybody have an idea how to solve this problem? At least the Firefox issue?

**Comment by olamothe** [comment]
Look here, you have to force a size on the svg container (most likely 100%) for your map when you instantiate the map.
https://github.com/simplegeo/polymaps/issues/115

It should be changed inside polymaps for a more permanent solution, but that should do the trick for a temporary fix.

**Comment by sidkshatriya** [comment]
Thanks @olamothe . The fix worked in Firefox 12. Awesome!

This leaves IE9. Does Polymaps even support IE9 ?

**Comment by sidkshatriya** [comment]
I was able to get this to work on IE 9 by using the master branch. (There is even a tag for it: 2.5.1 but polymaps.org is still offering 2.5.0 !!).

Summary:
- Works in Firefox using 1st workaround in https://github.com/simplegeo/polymaps/issues/115 . (You may additionally need to set the width and height on #map in pixels apart from svg setAttribute fix).
- Works in IE 9 by using master branch (or tag 2.5.1). [Currently 2.5.1 and master branch are the same]

**Comment by sennierer** [comment]
We are already using 2.5.1 and it is or was working on IE9, I cant check because I am working on a Mac.

The work around for Firefox 12 worked perfectly!! Thank you very much for the fast help!
