### ISSUE TITLE
Upgrade polymaps.org to 2.5.1 -- Currently examples breaking in IE9/Firefox

### ISSUE THREAD

**Issue by sidkshatriya** [simplegeo/polymaps#127]
I notice that polymaps.org is offering version 2.5.0 for download. Also it seems to be using 2.5.0 in the examples.

In the master branch, 2.5.1 has been tagged!! It fixes problems with IE9.

Please offer 2.5.1 for dowload and use 2.5.1 in all your examples on polymaps.org.

There is a simple fix for Firefox 11+ also (See https://github.com/simplegeo/polymaps/issues/115)

Maintainers: Your library does not look good if it breaks in IE9 and Firefox. I love your library!! Please make it look good -- It wont take much time to fix this!!

**Comment by IanWizard** [comment]
Second.

I was lookingfor a lib, and moved on when I saw all of the issues in FF.  Only now have I come back.

**Comment by mbostock** [comment]
Done. Sorry for the delay.
