### ISSUE TITLE
zoom center is broken when page is scrolled in WebKit

### ISSUE THREAD

**Issue by RandomEtc** [simplegeo/polymaps#15]
If the map is still visible but the page is scrolled, the mouse wheel zoom center is offset.

**Comment by RandomEtc** [comment]
This is the bug I thought was in Firefox, but Firefox turns out to be OK. I'm testing in Safari 5.0.1 (6533.17.8)

**Comment by mbostock** [comment]
It should be broken in Firefox too. We are using clientX/clientY in map.mouse, and should be using pageX/pageY.

**Comment by mbostock** [comment]
Actually `SVGLocatable.getScreenCTM` should be operating in the same coordinate space as `clientX` and `clientY`, so this may in fact be a bug in Safari.

**Comment by mbostock** [comment]
https://bugs.webkit.org/show_bug.cgi?id=44083

**Comment by mbostock** [comment]
This bug has now been fixed in WebKit, and I've implemented a workaround for earlier versions:

http://github.com/mbostock/polymaps/commit/86a1b8a3814ab843f84a12cf49911ac441fa84f1

**Comment by mbostock** [comment]
Fixed in 2.0.3.
