### ISSUE TITLE
IE9 doesn't support crossdomain xmlhttprequests

### ISSUE THREAD

**Issue by RandomEtc** [simplegeo/polymaps#16]
If the browser doesn't support them, can we throw an error?

Can we use jsonp to load data if crossdomain support isn't there, e.g. for the oakland clustering demo?

**Comment by mbostock** [comment]
Looks like we should be using `XDomainRequest`?

http://msdn.microsoft.com/en-us/library/cc288060(VS.85).aspx

**Comment by RandomEtc** [comment]
Yep! Fixed in ie9 branch. 

Note for future reference that XDomainRequest isn't a complete drop-in replacement for XMLHttpRequest. It doesn't support relative URLs and it doesn't have an onreadystatechange handler, only onload. Also it doesn't automatically parse XML - I'll add a new issue about that.
