### ISSUE TITLE
Arrow control: keypad + not working on Windows or Opera.

### ISSUE THREAD

**Issue by NelsonMinar** [simplegeo/polymaps#30]
Windows Vista, US keyboard, Google Chrome. Regular + and - work and numeric keypad - works, but not numeric keypad +. I believe the keyCode to listen for is 107; the arrow code is listening for 61.

**Comment by mbostock** [comment]
Looks like we are missing codes 43 (+) and 45 (-) for Opera, too.

http://unixpapa.com/js/key.html

**Comment by mbostock** [comment]
Fix here:

http://github.com/mbostock/polymaps/commit/a9137c1f6aaa8c3db1b0a4b5cab326a75a3e43e2

**Comment by mbostock** [comment]
Fixed in 2.1.0.
