### ISSUE TITLE
HTML documentation is a total mess

### ISSUE THREAD

**Issue by tungwaiyip** [simplegeo/polymaps#31]
The documentation does not format correctly. Text are overlapping. Tried in Chrome, Firefox, Opera. All of them have the same problem.  See http://tungwaiyip.info/2010/img/2010-09-21_polymaps_problem.png.
Version is 2.2.0.

**Comment by mbostock** [comment]
That's because you need to compile the documentation and then view it out of the `html/` directory, rather than `www/`. Or you can just visit the website http://polymaps.org/docs.

**Comment by tungwaiyip** [comment]
Thanks. I'm so dumb.
