### ISSUE TITLE
Can I zoom the map to the extent of a GeoJSON layer?

### ISSUE THREAD

**Issue by palewire** [simplegeo/polymaps#35]
So, i've created my map

<pre><code>    var po = org.polymaps;
    
    map = po.map()
        .container(document.getElementById("map-canvas").appendChild(po.svg("svg")))
        .zoomRange([1, 6])
        .zoom(4)
        .add(po.interact());
    map.add(po.image().url("http://s3.amazonaws.com/com.modestmaps.bluemarble/{Z}-r{Y}-c{X}.jpg"));
</code></pre>

And I've added a JSON layer:

<pre><code>
    data = po.geoJson().url("/json/?slug=foo").tile(false);
    map.add(data);
</code></pre>

How can I get the map to zoom to the extent of that layer?

**Comment by RandomEtc** [comment]
I'm not sure if any internal code already calculates the extent of the layer, so you probably need to loop over the features and calculate that yourself.

Once you have the min and max lat/lon of your features you can call `map.extent(newExtent)` to change the visible area. http://polymaps.org/docs/map.html#extent

**Comment by palewire** [comment]
Thanks. I think I got it by adding a load function my json that links to:

<pre><code>Array.max = function( array ){
    return Math.max.apply( Math, array );
};
Array.min = function( array ){
    return Math.min.apply( Math, array );
};

function load(e) {
  var x = Array();
  var y = Array();
  for (var i = 0; i &lt; e.features.length; i++) {
    var feature = e.features[i];
    var coords = feature.data.geometry.coordinates;
    var polygons = $.map(coords, function(a){return a});
    var points = $.map(polygons, function(a){return a});
    $.map(points, function(a){
        if(!isNaN(a[0])){x.push(a[0])}; 
        if(!isNaN(a[1])){y.push(a[1])};
    });
  }
  xMax = Array.max(x);
  xMin = Array.min(x);
  yMax = Array.max(y);
  yMin = Array.min(y);
  map.extent([{lon:xMin,lat:yMin},{lon:xMax,lat:yMax}])
}</code</pre>

**Comment by drewda** [comment]
Just for future reference here's a relevant bit of code: https://github.com/mbostock/polymaps/blob/master/examples/bounds/bounds.js
