### ISSUE TITLE
Cannot enter some characters

### ISSUE THREAD

**Issue by akidee** [simplegeo/polymaps#43]
```
map.add(po.arrow())
```

This prohibits that I can enter "=" (and probably other characters into a text box. Instead, it will zoom in. So please do not register any global key handlers for the map.

**Comment by RandomEtc** [comment]
You need to add a tabindex to the map container if you want to use arrow but don't want a global listener.

To put it another way, `po.arrow()` adds listeners to `map.focusableParent()`. The focusableParent is `window` unless the map container has a `tabindex`.

Docs for focusableParent are here:
http://polymaps.org/docs/map.html#focusableParent

Spec for tabindex is here:
http://www.w3.org/TR/html401/interact/forms.html#adef-tabindex

**Comment by RandomEtc** [comment]
You can see an example using tabindex here: http://bl.ocks.org/660054

**Comment by akidee** [comment]
You should make the script add the tabindex property to the map container (if it does not exist), because "polluting" the global space is not a good practice,
