### ISSUE TITLE
Map pixellated on Retina™© Display®

### ISSUE THREAD

**Issue by natevw** [simplegeo/polymaps#60]
When using Polymaps on a fourth-generation iPod touch or iPhone, the tiles are shown at twice the size they should be for smooth display.

**Comment by mbostock** [comment]
You can fix this easily by setting a zoom offset for the layer. For example:

```
map.add(po.image()
    .url(po.url("http://{S}tile.cloudmade.com"
    + "/1a1b06b230af4efdbb989ea99e9841af" // http://cloudmade.com/register
    + "/998/256/{Z}/{X}/{Y}.png")
    .hosts(["a.", "b.", "c.", ""]))
    .zoom(function(z) { return z + 1; }));
```

However, rather than using a fixed offset of +1, you'll probably want to compute the zoom offset using the `devicePixelRatio`:

```
var dz = Math.log(window.devicePixelRatio || 1) / Math.LN2;
```
