### ISSUE TITLE
firefox security error

### ISSUE THREAD

**Issue by till** [simplegeo/polymaps#75]
I just cloned the repository and used the example from `examples/marker/`. It's displaying a map with a couple markers in Chrome/Safari.

In Firefox, the map displays, but no markers are drawn.

This is the message I get:

```
Security Error: Content at file:///home/till/polymaps/examples/marker/marker.html may not load data from file:///home/till/polymaps/examples/marker/url(.
```

My Firefox' version is 3.6.17.

Generally incompatible, or is this a bug?

**Comment by mbostock** [comment]
This is probably expected behavior, due to the strict same-origin policy when running out of the local file system. To circumvent it, you can start a local web server and look at the examples there. For example, in the polymaps directory, type:

```
python -m SimpleHTTPServer 8888 &
```

Then go to http://localhost:8888 in your browser.

**Comment by RandomEtc** [comment]
Some examples require a webserver for the security permissions to work out.

Safari is generally a bit more permissive about testing locally with file:// urls.

You can use `python -m SimpleHTTPServer 8888` on the command line to server the current folder up to http://localhost:8888 in a web browser. That should allow most/all the examples to run.

**Comment by till** [comment]
Ah, didn't know that. Sounds like _security by obscurity_ -- I'll check that out.
