### ISSUE TITLE
Incomplete Documentation

### ISSUE THREAD

**Issue by jars** [simplegeo/polymaps#80]
When can we expect documentation on these?

URL: http://polymaps.org/docs/url.html
TRANSFORM: http://polymaps.org/docs/transform.html
QUEUE: http://polymaps.org/docs/queue.html
CACHE: http://polymaps.org/docs/cache.html

Cheers,

JoAr

**Comment by akidee** [comment]
+1 !

**Comment by tylerwolf** [comment]
+1

**Comment by DGuidi** [comment]
+1, but I must say that the better documentation you can find is the source code itself, so take a look here first ;)

**Comment by ghost** [comment]
"Polymaps is not being actively maintained by anyone at the moment." and the code itself is sometimes hard to read.
