### ISSUE TITLE
Remove Layer from Map

### ISSUE THREAD

**Issue by tyrauber** [simplegeo/polymaps#87]
What is the best method of removing a layer from the map?  

map.remove(id) 

Gives the following error:

```
 x.map is not a function
 x.map(null); 
```

map.remove(po.geoJson().id(id)); 

Does nothing.

document.getElementById('map').children[0].removeChild(document.getElementById(id));

Removes the layer from the Map, but when the user zooms, the browser reloads the url for all layers, even if they are no longer present.

**Comment by mbostock** [comment]
You need to remove the object you added previously. So, if you said:

``` javascript
var myLayer = po.geoJson();
map.add(myLayer);
```

Later you can say:

``` javascript
map.remove(myLayer);
```

**Comment by tyrauber** [comment]
Ah. Object, not layer id. That makes sense. 

I am adding layers through a function, so I had to globally declare the object through window[id] to make it available to my remove layer function... But it works.  Thank you.
