### ISSUE TITLE
Map Dispatch Example?

### ISSUE THREAD

**Issue by tyrauber** [simplegeo/polymaps#88]
I would like to access the map center lat, lon & zoom anytime the map changes (move, drag, zoom).  I understand map.center() accesses the lat and lon and map.zoom() accesses the zoom, but I am having difficulty dispatching the event on map change.

```
    map.dispatch("move", getCenter())
    map.dispatch.on('move', getCenter())
```

The above both fire off getCenter() when the page loads, but not upon any other map changes.

Is there an example of how to use map.dispatch to execute a function anytime the map changes (move, drag, zoom)?

**Comment by mbostock** [comment]
Yep, like this:

``` javascript
map.on("move", function() { console.log(map.center()); });
```

**Comment by tyrauber** [comment]
Of course. Got to wrap it in, function(){ }. Like with D3 onClick events. I should have known. 

Works beautifully. Thanks.
